### ISSUE TITLE
Solutions approval

### ISSUE THREAD

**Issue by thejerome** [tcibinan/flaxo#4]
It would be good to add a column for a manual check.
Meaning - tutor can review pull request and consider it good, so he can just can hit a checkbox or choose an option something like that just to remember that check was done and its result is good or not.
Or at least it can be a short comment column.

**Comment by thejerome** [comment]
One more option is to have an ability to commit the result for particular pair of task and student - just having a button to say "It is cheked, result is set" that will make the line readonly and will change it style so it can be distinguished from lines that are still open for modification. Of course such closing should be revertable.

**Comment by tcibinan** [comment]
GitHub has its own mechanism of manual checking - pull requests reviews. I suppose the most natural way for Flaxo is to synchronize its checks with GitHub ones.

**Comment by tcibinan** [comment]
The current solution looks like the following. 

The task statistics table should be expanded with an additional *approved* column which basically is a set of checkboxes. If checkbox is checked then it means that a solution is approved. If it is not then solution is not approved or requires changes.

![updated task statistics table](https://user-images.githubusercontent.com/16464586/46697956-83f8b580-cc1e-11e8-8c2c-175be32d964f.png)

If user toggles checkbox to an active state then flaxo will *create an approval review* on the pull request.
If user toggles checkbox to an inactive state then after user enters small review message flaxo will *create a changes required review* on the pull request.

**Comment by tcibinan** [comment]
Done in 6365ef1cdfdf3472e87838cf5346eeba7c78bdf0 ... d70fb35e0f418c8e0fefab658629d6853936dc6f.
