### ISSUE TITLE
Regular expressions of files for plagiarism analysis

### ISSUE THREAD

**Issue by nikita715** [tcibinan/flaxo#66]
Repository in Gitplag has an array of regular expressions that are used to define whether a file has to be stored in the file storage and used in plagiarism analysis. Flaxo course may have a parameter for regular expressions that have to be used in plagiarism analysis using Gitplag or the built-in Moss analysis.

**Comment by tcibinan** [comment]
It can be specified in the corresponding course setting such as *plagiarism analysis file patterns* which defaults to course main language file extensions.
